queue_rules:
  - name: Exercism Solutions Syncer
    queue_conditions:
      - and:
          - author = exercism-solutions-syncer[bot]
merge_protections_settings:
  auto_merge_conditions: true
  reporting_method: check-runs
